print('1) Create new database')
print('2) Open database')
print('3) Close database')
print('4) Display record')
print('5) Update record')
print('6) Create report')
print('7) Add record')
print('8) Delete record')
print('9) Quit')
choice = input()